// mobile/src/chat/ContextRing.tsx
import { View } from 'react-native';
import Svg, { Circle, G, Text as SvgText } from 'react-native-svg';
import { StyleSheet, useUnistyles } from 'react-native-unistyles';
import * as m from '../paraglide/messages';

// Anel de uso de contexto (irmão do ContextRing.svelte da PWA): mesma geometria em viewBox 24,
// arco começa no topo (rotate -90) e cresce anti-horário, e a % vai DENTRO do círculo.
//
// Em repouso o arco é neutro, não indigo: o indigo é reservado pro que é clicável, e o anel é
// mostrador (mesma escolha da PWA). Aviso a partir de 70%, erro a partir de 90%.
//
// Sem leitura o anel não desenha nada: um círculo vazio no cabeçalho não informa e ainda ocupa
// lugar de quem informa.
const R = 9;
const C = 2 * Math.PI * R;

export function ContextRing({ pct, size = 24 }: { pct?: number | null; size?: number }) {
  const { theme } = useUnistyles();
  if (typeof pct !== 'number' || !isFinite(pct)) return null;
  const value = Math.min(100, Math.max(0, pct));
  const offset = C * (1 - value / 100);
  const cor =
    value >= 90
      ? theme.tokens.status.error
      : value >= 70
        ? theme.tokens.status.warning
        : theme.tokens.text.secondary;
  return (
    <View
      style={styles.wrap}
      accessible={true}
      accessibilityLabel={m.ctx_uso_contexto()}
      accessibilityValue={{ min: 0, max: 100, now: Math.round(value) }}
    >
      <Svg width={size} height={size} viewBox="0 0 24 24">
        <Circle cx="12" cy="12" r={R} stroke={theme.tokens.border.default} strokeWidth={3} fill="none" />
        <G transform="rotate(-90 12 12)">
          <Circle
            cx="12"
            cy="12"
            r={R}
            stroke={cor}
            strokeWidth={3}
            strokeLinecap="round"
            strokeDasharray={C}
            strokeDashoffset={offset}
            fill="none"
          />
        </G>
        {/* só o número, sem '%': o anel já diz que é percentual, e o '%' não caberia */}
        <SvgText x="12" y="12" fontSize="9" fontWeight="600" fill={cor} textAnchor="middle" alignmentBaseline="central">
          {Math.round(value)}
        </SvgText>
      </Svg>
    </View>
  );
}

const styles = StyleSheet.create(() => ({
  wrap: {
    alignItems: 'center',
    justifyContent: 'center',
  },
}));

// frontend/src/components/ContextRing.svelte
<script lang="ts">
  // Ring de uso de contexto: a % vai DENTRO do circulo (centralizada). Cor muda so nos limiares.
  import * as m from '../paraglide/messages';
  interface Props {
    pct?: number | null;
    size?: number;
  }
  let { pct = null, size = 26 }: Props = $props();

  const R = 9;
  const C = 2 * Math.PI * R;
  const known = $derived(typeof pct === 'number' && isFinite(pct as number));
  const value = $derived(known ? Math.min(100, Math.max(0, pct as number)) : 0);
  const offset = $derived(C * (1 - value / 100));
  const tone = $derived(value >= 90 ? 'error' : value >= 70 ? 'warn' : 'ok');
</script>

<div
  class="ring tone-{tone}"
  role="meter"
  aria-valuemin="0"
  aria-valuemax="100"
  aria-valuenow={known ? Math.round(value) : undefined}
  aria-label={m.ctx_uso_contexto()}
>
  <svg width={size} height={size} viewBox="0 0 24 24" aria-hidden="true">
    <circle cx="12" cy="12" r={R} class="track" />
    {#if known}
      <circle
        cx="12"
        cy="12"
        r={R}
        class="arc"
        stroke-dasharray={C}
        stroke-dashoffset={offset}
        transform="rotate(-90 12 12)"
      />
    {/if}
    <text x="12" y="12.5" class="ring-text" text-anchor="middle" dominant-baseline="middle">
      {known ? Math.round(value) : '—'}
    </text>
  </svg>
</div>

<style>
  .ring {
    display: inline-flex;
    align-items: center;
    flex-shrink: 0;
  }
  svg { flex-shrink: 0; }
  .track {
    fill: none;
    stroke: var(--border-default);
    stroke-width: 3;
  }
  .arc {
    fill: none;
    stroke-width: 3;
    stroke-linecap: round;
    transition: stroke-dashoffset 600ms var(--ease-out), stroke 300ms ease;
  }
  /* % dentro do anel: numero (sem '%' pra caber); o anel ja diz que e percentual. */
  .ring-text {
    font-family: var(--font-mono);
    font-size: 9px;
    font-weight: 600;
    fill: var(--text-secondary);
  }
  /* Repouso = neutro, igual ao mostrador de quota do NavBar (RateChips): um vocabulario so de
     medidor. O indigo fica reservado pro que e clicavel. */
  .tone-ok .arc { stroke: var(--text-secondary); }
  .tone-warn .arc { stroke: var(--warning); }
  .tone-error .arc { stroke: var(--error); }
  .tone-warn .ring-text { fill: var(--warning); }
  .tone-error .ring-text { fill: var(--error); }
</style>
