// mobile/src/chat/OptionButtons.tsx
import { Pressable, Text, View } from 'react-native';
import { StyleSheet, useUnistyles } from 'react-native-unistyles';
import { kindOf, isPermission } from '@hangar/core';
import * as m from '../paraglide/messages';

interface Props {
  question: string;
  options: string[];
  onSelect: (n: number) => void;
  onCancel: () => void;
}

export function OptionButtons({ question, options, onSelect, onCancel }: Props) {
  const { theme } = useUnistyles();
  const permission = isPermission(options);
  const kinds = options.map((o) => kindOf(o));

  return (
    <View style={styles.wrap}>
      {permission ? (
        <View style={[styles.permChip, { backgroundColor: theme.tokens.accent.dim }]}>
          <Text style={[styles.permTxt, { color: theme.tokens.accent.base }]}>{m.permissao_pedido()}</Text>
        </View>
      ) : null}
      <Text style={[styles.question, { color: theme.tokens.text.primary }]}>
        {question.split('`').map((part, i) =>
          i % 2 === 1 ? (
            <Text key={i} style={[styles.qCode, { backgroundColor: theme.tokens.bg.elevated, color: theme.tokens.text.primary }]}>
              {part}
            </Text>
          ) : (
            part
          ),
        )}
      </Text>
      <View style={styles.list}>
        {options.map((opt, i) => {
          const kind = kinds[i];
          const isAllow = permission && kind === 'allow';
          const isAlways = permission && kind === 'always';
          const isDeny = permission && kind === 'deny';
          return (
            <Pressable
              key={i}
              onPress={() => onSelect(i + 1)}
              style={[
                styles.btn,
                { backgroundColor: theme.tokens.bg.elevated, borderColor: theme.tokens.border.default },
                isAllow && { backgroundColor: theme.tokens.accent.base, borderColor: theme.tokens.accent.base },
                isAlways && { backgroundColor: theme.tokens.accent.dim, borderColor: theme.tokens.accent.base },
                isDeny && { borderColor: theme.tokens.status.error },
              ]}
              accessibilityRole="button"
            >
              <Text
                style={[
                  styles.num,
                  { color: theme.tokens.text.secondary },
                  isAllow && { color: '#fff' },
                  isAlways && { color: theme.tokens.accent.base },
                  isDeny && { color: theme.tokens.status.error },
                ]}
              >
                {i + 1}.
              </Text>
              <Text
                style={[
                  styles.optTxt,
                  { color: theme.tokens.text.primary },
                  isAllow && { color: '#fff' },
                  isAlways && { color: theme.tokens.accent.base },
                  isDeny && { color: theme.tokens.status.error },
                ]}
              >
                {opt}
              </Text>
            </Pressable>
          );
        })}
        <Pressable
          onPress={onCancel}
          style={[styles.btn, styles.btnCancel, { borderColor: theme.tokens.status.error }]}
          accessibilityRole="button"
        >
          <Text style={[styles.num, { color: theme.tokens.status.error }]}>✕</Text>
          <Text style={[styles.optTxt, { color: theme.tokens.status.error }]}>{m.comum_cancelar()}</Text>
        </Pressable>
      </View>
    </View>
  );
}

const styles = StyleSheet.create((theme) => ({
  wrap: {
    padding: theme.base.space[3],
    gap: theme.base.space[3],
  },
  permChip: {
    alignSelf: 'flex-start',
    borderRadius: theme.base.radius.full,
    paddingHorizontal: theme.base.space[2],
    paddingVertical: 4,
  },
  permTxt: {
    fontSize: theme.base.text.xs,
    fontWeight: '600',
  },
  question: {
    fontSize: theme.base.text.base,
    fontWeight: '500',
    lineHeight: 22,
  },
  qCode: {
    fontFamily: theme.base.fontMono,
    fontSize: 13,
    paddingHorizontal: 4,
    borderRadius: 4,
  },
  list: {
    gap: theme.base.space[2],
  },
  btn: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.base.space[3],
    paddingHorizontal: theme.base.space[3],
    borderWidth: 1,
    borderRadius: theme.base.radius.lg,
  },
  btnCancel: {
    borderColor: theme.tokens.status.error,
  },
  num: {
    fontFamily: theme.base.fontMono,
    fontSize: theme.base.text.sm,
    minWidth: 20,
  },
  optTxt: {
    fontSize: theme.base.text.base,
    flex: 1,
  },
}));

// frontend/src/components/OptionButtons.svelte
<script lang="ts">
  import * as m from '../paraglide/messages';
  import { kindOf, isPermission as isPermissionFn } from '@hangar/core';
  interface Props {
    question: string;
    options: string[];
    onSelect: (index: number) => void;
    onCancel: () => void;
  }
  let { question, options, onSelect, onCancel }: Props = $props();

  const kinds = $derived(options.map(kindOf));
  const isPermission = $derived(isPermissionFn(options));
</script>

<div class="options-wrap">
  {#if isPermission}
    <span class="perm-chip">{m.permissao_pedido()}</span>
  {/if}
  <p class="question">
    <!-- Trechos entre crases (comando/arquivo do pedido) viram <code> — legivel no celular. -->
    {#each question.split('`') as part, i}{#if i % 2 === 1}<code class="q-code">{part}</code>{:else}{part}{/if}{/each}
  </p>
  <div class="options-list">
    {#each options as opt, i}
      <button
        class="option-btn"
        class:option-btn--allow={isPermission && kinds[i] === 'allow'}
        class:option-btn--always={isPermission && kinds[i] === 'always'}
        class:option-btn--deny={isPermission && kinds[i] === 'deny'}
        style="animation-delay: {i * 40}ms"
        onclick={() => onSelect(i + 1)}
      >
        <span class="opt-num">{i + 1}.</span>
        <span class="opt-text">{opt}</span>
      </button>
    {/each}
    <button
      class="option-btn option-btn--cancel"
      style="animation-delay: {options.length * 40}ms"
      onclick={onCancel}
    >
      <span class="opt-num">✕</span>
      <span class="opt-text">{m.comum_cancelar()}</span>
    </button>
  </div>
</div>

<style>
  .options-wrap {
    padding: var(--space-4) var(--space-4) var(--space-6);
  }

  .question {
    font-size: var(--text-lg);
    color: var(--text-primary);
    font-weight: 500;
    margin-bottom: var(--space-4);
    line-height: 1.4;
  }

  /* Pedido de permissao: chip + botoes com semantica visual (permitir/sempre/negar). */
  .perm-chip {
    display: inline-block;
    font-size: var(--text-xs);
    font-weight: 600;
    color: var(--accent);
    background: var(--accent-dim);
    border-radius: var(--radius-full);
    padding: 2px 10px;
    margin-bottom: var(--space-2);
  }
  .q-code {
    font-family: var(--font-mono);
    font-size: 0.85em;
    background: var(--surface-raised);
    padding: 2px 6px;
    border-radius: 4px;
    word-break: break-all;
  }
  .option-btn--allow {
    background: var(--accent);
    border-color: var(--accent);
  }
  .option-btn--allow .opt-text, .option-btn--allow .opt-num { color: #fff; }
  .option-btn--allow:active { background: var(--accent-press); }
  .option-btn--always {
    background: var(--accent-dim);
    border-color: var(--accent);
  }
  .option-btn--always .opt-text { color: var(--accent); }
  .option-btn--deny {
    border-color: var(--error);
  }
  .option-btn--deny .opt-text, .option-btn--deny .opt-num { color: var(--error); }

  .options-list {
    display: flex;
    flex-direction: column;
    gap: var(--space-2);
  }

  .option-btn {
    width: 100%;
    min-height: 52px;
    background: var(--surface-raised);
    border: 1px solid var(--border-default);
    border-radius: var(--radius-lg);
    display: flex;
    align-items: center;
    gap: var(--space-3);
    padding: 0 var(--space-4);
    text-align: left;
    cursor: pointer;
    transition: background 180ms ease-out;
    animation: option-in 220ms ease-out both;
  }

  .option-btn:active {
    background: var(--bg-hover);
  }

  .option-btn--cancel {
    border-color: var(--error);
    color: var(--error);
  }

  .opt-num {
    font-family: var(--font-mono);
    font-size: var(--text-sm);
    color: var(--text-secondary);
    flex-shrink: 0;
    min-width: 20px;
  }

  .option-btn--cancel .opt-num {
    color: var(--error);
  }

  .opt-text {
    font-size: var(--text-base);
    color: var(--text-primary);
  }

  .option-btn--cancel .opt-text {
    color: var(--error);
  }
</style>
