// mobile/src/features/config/TranscriptionProviders.tsx
import { useCallback, useEffect, useRef, useState, type ReactNode } from 'react';
import { Linking, Pressable, Text, TextInput, View } from 'react-native';
import { StyleSheet, useUnistyles } from 'react-native-unistyles';
import {
  editTranscriptionProviderKey, editTranscriptionProviderTarget, fmtWhen, getTranscriptionProvidersStatus, moveTranscriptionProvider,
  parseTranscriptionProviders, transcriptionProviderKeepsKey, testTranscriptionProvider,
  type TranscriptionProviderConfig, type TranscriptionProviderStatus,
} from '@hangar/core';
import { BlockHead, Box, useInputStyle } from './ServerConfigParts';
import { Pill } from './PageHeader';
import { Segmented } from './Segmented';
import { useSettingsColors } from './colors';
import { PROVIDERS, type ServerConfig } from './serverConfig';
import { Icon, type IconName } from '../../ui/Icon';
import * as m from '../../paraglide/messages';
import { pickFile } from '../../ui/attachmentPicker';

type Status = { state: 'loading' } | { state: 'error'; error: string } | { state: 'ready'; byId: Record<string, TranscriptionProviderStatus> };

/**
 * Serviços de transcrição em ordem (`render_providers` do Rust): o primeiro transcreve, e quem falha ou fica sem cota
 * passa a vez. Servidor cuja leitura não trouxe a lista não mostra o bloco.
 */
export function TranscriptionProviders({ cfg }: { cfg: ServerConfig }) {
  const { theme } = useUnistyles();
  const c = useSettingsColors();
  const input = useInputStyle();
  const [status, setStatus] = useState<Status>({ state: 'loading' });
  const [tests, setTests] = useState<Record<string, { running: boolean; text: string; error: string }>>({});
  const selectingAudio = useRef(false);
  const currentServer = useRef(cfg.server);
  currentServer.current = cfg.server;
  const mounted = useRef(true);
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; }; }, []);
  const server = cfg.server;
  useEffect(() => { setTests({}); }, [server]);
  const present = PROVIDERS in cfg.fields;

  const loadStatus = useCallback(() => {
    if (!server) return () => {};
    let live = true;
    setStatus({ state: 'loading' });
    getTranscriptionProvidersStatus(server)
      .then((r) => { if (live) setStatus({ state: 'ready', byId: Object.fromEntries(r.providers.map((p) => [p.id, p])) }); })
      .catch((e: unknown) => {
        if (live) setStatus({ state: 'error', error: e instanceof Error && e.message ? e.message : m.erro_desconhecido() });
      });
    return () => { live = false; };
  }, [server]);

  // Relê a cada leitura boa da página (abrir e Salvar): a espera muda com a lista.
  useEffect(() => (cfg.load.status === 'ready' && present ? loadStatus() : undefined),
    [cfg.load.status, cfg.fields, present, loadStatus]);

  if (!present) return null;
  const list = parseTranscriptionProviders(cfg.current(PROVIDERS));
  const stored = parseTranscriptionProviders(cfg.fields[PROVIDERS]?.valor);
  const stage = (next: TranscriptionProviderConfig[]) => cfg.stage(PROVIDERS, next);
  const edit = (i: number, item: TranscriptionProviderConfig) => stage(list.map((p, n) => (n === i ? item : p)));
  const kinds = [{ v: 'openai', label: m.native_voice_provider_kind_openai() }, { v: 'elevenlabs', label: m.native_voice_provider_kind_elevenlabs() },
    { v: 'whisper_cpp', label: m.native_voice_provider_kind_whisper() }] as const;
  const testAudio = async (id: string) => {
    if (!server || tests[id]?.running || selectingAudio.current) return;
    selectingAudio.current = true;
    try {
      const file = await pickFile().finally(() => { selectingAudio.current = false; });
      if (!file || !mounted.current || currentServer.current !== server) return;
      setTests((old) => ({ ...old, [id]: { running: true, text: '', error: '' } }));
      const audio = await fetch(file.uri).then((r) => r.blob());
      const result = await testTranscriptionProvider(id, audio, file.name, server);
      if (mounted.current && currentServer.current === server) {
        setTests((old) => ({ ...old, [id]: { running: false, text: result.text, error: result.aviso || '' } }));
        loadStatus();
      }
    } catch (error) {
      if (mounted.current && currentServer.current === server) setTests((old) => ({ ...old,
        [id]: { running: false, text: '', error: error instanceof Error ? error.message : m.erro_desconhecido() } }));
    }
  };
  const now = Date.now() / 1000;
  const add = () => stage([...list, {
    // ponytail: relógio + sorteio; dois toques nunca colidem na prática.
    id: `p${Date.now().toString(16)}${Math.random().toString(16).slice(2, 6)}`,
    kind: 'openai', name: '', base_url: '', api_key: '', model: '',
  }]);
  const iconButton = (icon: IconName, label: string, onPress: () => void, disabled: boolean) => (
    <Pressable onPress={onPress} disabled={disabled} hitSlop={6} style={[styles.iconBtn, disabled && styles.off]}
      accessibilityRole="button" accessibilityLabel={label} accessibilityState={{ disabled }}>
      <Icon name={icon} size={16} color={c.muted} />
    </Pressable>
  );

  return (
    <>
      <BlockHead title={m.native_voice_providers()} help={m.native_voice_providers_help()}
        right={PROVIDERS in cfg.draft ? <Pill label={m.native_server_undo()} onPress={() => cfg.unstage(PROVIDERS)} /> : null} />
      <Box>
        {list.length === 0 ? (
          <View style={[styles.line, { borderTopColor: c.border }]}>
            <Text style={[styles.help, { color: c.muted }]}>{m.native_voice_providers_empty()}</Text>
          </View>
        ) : null}
        {list.map((p, i) => {
          const state = status.state === 'ready' ? status.byId[p.id] : undefined;
          const name = p.name.trim() || state?.name || (p.kind === 'whisper_cpp' ? m.native_voice_provider_kind_whisper() : p.kind === 'elevenlabs'
            ? m.native_voice_provider_kind_elevenlabs() : m.native_voice_provider_kind_openai());
          const title = `${i + 1}. ${name}`;
          const until = state?.waiting_until && state.waiting_until > now ? state.waiting_until : null;
          const waiting = until ? m.native_voice_provider_waiting({ until: fmtWhen(until) }) : null;
          const saved = stored.find((s) => s.id === p.id);
          const mask = saved?.api_key || undefined;
          const keeps = transcriptionProviderKeepsKey(p, saved);
          const keptMask = mask && p.api_key === mask ? mask : null;
          return (
            <View key={p.id} style={[styles.line, styles.item, { borderTopColor: c.border }]}>
              <View style={styles.head}>
                <Text numberOfLines={1} style={[styles.title, { color: c.text }]}>{title}</Text>
                {iconButton('ArrowUp', m.native_voice_provider_up({ name }), () => stage(moveTranscriptionProvider(list, i, -1)), i === 0)}
                {iconButton('ArrowDown', m.native_voice_provider_down({ name }), () => stage(moveTranscriptionProvider(list, i, 1)), i === list.length - 1)}
                <Pressable onPress={() => stage(list.filter((_, n) => n !== i))} hitSlop={6} style={styles.remove}
                  accessibilityRole="button" accessibilityLabel={m.native_voice_provider_remove({ name })}>
                  <Icon name="X" size={14} color={c.muted} />
                  <Text style={[styles.removeText, { color: c.muted }]}>{m.native_server_remove()}</Text>
                </Pressable>
              </View>
              {waiting ? (
                <Text accessibilityLiveRegion="polite" style={[styles.small, { color: theme.tokens.status.warning }]}>
                  {state?.reason ? `${waiting}: ${state.reason}` : waiting}
                </Text>
              ) : null}
              <Segmented options={kinds} value={p.kind} label={title}
                onChange={(v) => edit(i, editTranscriptionProviderTarget(p, { kind: v }, saved))} />
              {p.kind === 'openai' ? (
                <Labeled label={m.native_voice_provider_endpoint()}>
                  <TextInput {...input} accessibilityLabel={`${m.native_voice_provider_endpoint()}, ${title}`}
                    placeholder="https://api.groq.com/openai/v1" autoCapitalize="none" autoCorrect={false} keyboardType="url"
                    value={p.base_url} onChangeText={(t) => edit(i, editTranscriptionProviderTarget(p, { base_url: t }, saved))} />
                </Labeled>
              ) : null}
              {p.kind === 'whisper_cpp' ? <>
                <Text style={[styles.help, { color: c.muted }]}>{m.native_voice_provider_local_help({ server: server?.label || m.native_voice_provider_current_server() })}</Text>
                <Pressable accessibilityRole="link" onPress={() => void Linking.openURL('https://github.com/ggml-org/whisper.cpp')}>
                  <Text style={[styles.help, { color: c.text }]}>{m.native_voice_provider_official()}</Text>
                </Pressable>
                {[
                  { field: 'executable_path' as const, label: m.native_voice_provider_executable(), placeholder: 'whisper-server' },
                  { field: 'model_path' as const, label: m.native_voice_provider_model_file(), placeholder: 'ggml-small.bin' },
                  { field: 'language' as const, label: m.native_voice_provider_language(), placeholder: 'pt' },
                  { field: 'converter_path' as const, label: m.native_voice_provider_converter(), placeholder: 'ffmpeg' },
                ].map((item) => <Labeled key={item.field} label={item.label}>
                  <TextInput {...input} accessibilityLabel={`${item.label}, ${title}`} autoCapitalize="none" autoCorrect={false}
                    placeholder={item.placeholder} value={p[item.field] || ''} onChangeText={(value) => edit(i, { ...p, [item.field]: value })} />
                </Labeled>)}
                {state?.error ? <Text accessibilityRole="alert" style={[styles.help, { color: theme.tokens.status.error }]}>{state.error}</Text> : null}
              </> : <>
              <Labeled label={p.kind === 'openai' ? m.native_voice_provider_key_optional() : m.native_voice_provider_key()}>
                {/* Como o ConfigRow: mostra só o digitado; apagar volta à máscara, que mantém a chave guardada. */}
                <TextInput {...input} accessibilityLabel={`${p.kind === 'openai' ? m.native_voice_provider_key_optional() : m.native_voice_provider_key()}, ${title}`} secureTextEntry
                  autoCapitalize="none" autoCorrect={false} textContentType="none" autoComplete="off"
                  placeholder={mask ? m.native_server_secret_paste_new() : m.native_server_secret_paste()}
                  value={p.api_key === mask ? '' : p.api_key} onChangeText={(t) => edit(i, editTranscriptionProviderKey(p, t, keeps ? mask : undefined))} />
              </Labeled>
              {keptMask ? (
                <Text style={[styles.small, { color: c.muted }]}>
                  <Text style={{ fontFamily: theme.base.fontMono }}>{keptMask}</Text> · {m.native_server_secret_set()}
                </Text>
              ) : null}
              {p.api_key || p.kind !== 'elevenlabs' ? null : (
                <Text accessibilityRole="alert" style={[styles.small, { color: theme.tokens.status.warning }]}>{m.native_voice_provider_missing_key()}</Text>
              )}
              <Labeled label={m.native_voice_provider_model()}>
                {/* Modelo padrão do servidor: identificador, não frase de tela. */}
                <TextInput {...input} accessibilityLabel={`${m.native_voice_provider_model()}, ${title}`}
                  placeholder={p.kind === 'elevenlabs' ? 'scribe_v2' : 'whisper-large-v3'}
                  autoCapitalize="none" autoCorrect={false} value={p.model} onChangeText={(t) => edit(i, { ...p, model: t })} />
              </Labeled>
              </>}
              <Pill label={tests[p.id]?.running ? m.native_voice_provider_test_running() : m.native_voice_provider_test_audio()}
                disabled={PROVIDERS in cfg.draft || tests[p.id]?.running} onPress={() => void testAudio(p.id)} />
              {PROVIDERS in cfg.draft ? <Text style={[styles.help, { color: c.muted }]}>{m.native_voice_provider_test_saved()}</Text> : null}
              {tests[p.id]?.error ? <Text accessibilityRole="alert" style={[styles.help, { color: theme.tokens.status.error }]}>{tests[p.id].error}</Text> : null}
              {tests[p.id]?.text ? <View><Text accessibilityLiveRegion="polite" style={[styles.help, { color: c.muted }]}>{m.native_voice_provider_test_success()}</Text>
                <Text style={[styles.help, { color: c.text }]}>{tests[p.id].text}</Text></View> : null}
            </View>
          );
        })}
        <View style={[styles.line, styles.addLine, { borderTopColor: c.border }]}>
          <Pill icon="Plus" label={m.native_voice_provider_add()} onPress={add} />
        </View>
      </Box>
      {status.state === 'error' ? (
        <View style={styles.errorLine}>
          <Text accessibilityRole="alert" style={[styles.help, styles.flex, { color: theme.tokens.status.error }]}>
            {m.native_voice_providers_status_failed({ error: status.error })}
          </Text>
          <Pill label={m.native_server_retry()} onPress={() => { loadStatus(); }} />
        </View>
      ) : null}
    </>
  );
}

function Labeled({ label, children }: { label: string; children: ReactNode }) {
  const c = useSettingsColors();
  return (
    <View style={styles.labeled}>
      <Text style={[styles.small, { color: c.muted }]}>{label}</Text>
      {children}
    </View>
  );
}

const styles = StyleSheet.create({
  line: { borderTopWidth: 1, paddingVertical: 14, paddingHorizontal: 16 },
  item: { gap: 10 },
  addLine: { paddingVertical: 10, flexDirection: 'row' },
  head: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  title: { flex: 1, minWidth: 0, fontSize: 15, fontWeight: '500' },
  iconBtn: { width: 32, height: 32, alignItems: 'center', justifyContent: 'center' },
  off: { opacity: 0.4 },
  remove: { flexDirection: 'row', alignItems: 'center', gap: 4, height: 32, paddingHorizontal: 6 },
  removeText: { fontSize: 13.5, fontWeight: '500' },
  labeled: { gap: 4 },
  small: { fontSize: 13.5, lineHeight: 17 },
  help: { fontSize: 14, lineHeight: 18 },
  errorLine: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 4 },
  flex: { flex: 1 },
});

// frontend/src/components/settings/TranscriptionProviders.svelte
<script lang="ts">
  import type { ConfigServidorStore } from '../../lib/serverConfig.svelte';
  import SegmentedPicker from '../SegmentedPicker.svelte';
  import {
    editTranscriptionProviderKey, editTranscriptionProviderTarget, getTranscriptionProvidersStatus, testTranscriptionProvider,
    moveTranscriptionProvider, parseTranscriptionProviders, transcriptionProviderKeepsKey, transcriptionProviderLabel,
    type TranscriptionProviderConfig, type TranscriptionProviderKind, type TranscriptionProviderStatus,
  } from '@hangar/core';
  import { intlLocale } from '../../lib/locale';
  import * as m from '../../paraglide/messages';

  // Ordem da lista = ordem de tentativa. O nome do serviço aparece só no item, nunca no rótulo da
  // capacidade (a seção continua se chamando "Transcrição").
  interface Props { store: ConfigServidorStore }
  let { store }: Props = $props();
  let destroyed = false;
  $effect(() => () => { destroyed = true; });
  const audioInputs: Record<string, HTMLInputElement | undefined> = {};
  let tests = $state<Record<string, { running: boolean; error: string; text: string }>>({});

  async function testAudio(id: string, file: File | undefined) {
    if (!file || tests[id]?.running) return;
    const server = store.alvo;
    const saved = JSON.stringify(salvos.get(id));
    tests[id] = { running: true, error: '', text: '' };
    try {
      const result = await testTranscriptionProvider(id, file, file.name, server);
      if (destroyed || store.alvo !== server || JSON.stringify(salvos.get(id)) !== saved) return;
      tests[id] = { running: false, error: result.aviso || '', text: result.text };
      releitura++;
    } catch (error) {
      if (!destroyed && store.alvo === server) tests[id] = { running: false,
        error: error instanceof Error ? error.message : m.erro_desconhecido(), text: '' };
    } finally {
      if (!destroyed && tests[id]?.running) tests[id] = { running: false, error: '', text: '' };
    }
  }
  const CHAVE = 'transcription_providers';

  const lista = $derived(parseTranscriptionProviders(store.valorBruto(CHAVE)));
  // Item salvo, por id: a máscara da chave devolvida intacta faz o backend manter a chave antiga.
  const salvos = $derived(new Map(parseTranscriptionProviders(store.campos[CHAVE]?.valor).map((p) => [p.id, p])));

  function gravar(nova: TranscriptionProviderConfig[]) { store.setRascunho(CHAVE, nova); }
  function atualizar(i: number, novo: TranscriptionProviderConfig) {
    gravar(lista.map((p, j) => (j === i ? novo : p)));
  }
  function remover(i: number) { gravar(lista.filter((_, j) => j !== i)); }
  function adicionar() {
    // crypto.randomUUID não existe fora de contexto seguro (PWA por http na rede local).
    const id = Math.random().toString(36).slice(2, 10);
    gravar([...lista, { id, kind: 'openai', name: '', base_url: '', api_key: '', model: '' }]);
  }

  // Espera por cota, lida do servidor editado. Relê quando os campos são trocados (abrir e salvar).
  let status = $state<TranscriptionProviderStatus[] | null>(null);
  let statusErro = $state('');
  let releitura = $state(0);
  $effect(() => {
    void store.campos;
    void releitura;
    if (store.carregando) return;
    let vivo = true;
    statusErro = '';
    getTranscriptionProvidersStatus(store.alvo)
      .then((r) => { if (vivo) status = r.providers; })
      .catch((e) => { if (vivo) statusErro = e instanceof Error ? e.message : String(e); });
    return () => { vivo = false; };
  });
  function emEspera(id: string): TranscriptionProviderStatus | null {
    const s = status?.find((x) => x.id === id);
    return s?.waiting_until && s.waiting_until * 1000 > Date.now() ? s : null;
  }
  const hora = (t: number) => new Date(t * 1000).toLocaleString(intlLocale(), { dateStyle: 'short', timeStyle: 'short' });
  const opcoesTipo = $derived([
    { v: 'openai' as TranscriptionProviderKind, label: m.native_voice_provider_kind_openai(), aria: m.native_voice_provider_kind_openai() },
    { v: 'elevenlabs' as TranscriptionProviderKind, label: m.native_voice_provider_kind_elevenlabs(), aria: m.native_voice_provider_kind_elevenlabs() },
    { v: 'whisper_cpp' as TranscriptionProviderKind, label: m.native_voice_provider_kind_whisper(), aria: m.native_voice_provider_kind_whisper() },
  ]);
</script>

<div class="servicos">
  <p class="ajuda">{m.native_voice_providers_help()}</p>
  {#if statusErro}
    <p class="aviso erro" role="alert">
      {m.native_voice_providers_status_failed({ error: statusErro })}
      <button class="link-btn" onclick={() => releitura++}>{m.config_server_tentar_de_novo()}</button>
    </p>
  {/if}
  {#if lista.length === 0}
    <p class="aviso">{m.native_voice_providers_empty()}</p>
  {:else}
    <ol class="lista">
      {#each lista as p, i (p.id)}
        {@const nome = transcriptionProviderLabel(p)}
        {@const espera = emEspera(p.id)}
        {@const salvo = salvos.get(p.id)}
        {@const mascara = salvo?.api_key || undefined}
        {@const mantem = transcriptionProviderKeepsKey(p, salvo)}
        <li class="item">
          <div class="item-cabeca">
            <span class="nome">{nome}</span>
            <div class="acoes">
              <button class="mini" onclick={() => gravar(moveTranscriptionProvider(lista, i, -1))} disabled={i === 0}
                aria-label={m.native_voice_provider_up({ name: nome })} title={m.native_voice_provider_up({ name: nome })}>↑</button>
              <button class="mini" onclick={() => gravar(moveTranscriptionProvider(lista, i, 1))} disabled={i === lista.length - 1}
                aria-label={m.native_voice_provider_down({ name: nome })} title={m.native_voice_provider_down({ name: nome })}>↓</button>
              <button class="mini" onclick={() => remover(i)}
                aria-label={m.native_voice_provider_remove({ name: nome })} title={m.native_voice_provider_remove({ name: nome })}>✕</button>
            </div>
          </div>
          {#if espera}
            <p class="espera" role="status">
              {m.native_voice_provider_waiting({ until: hora(espera.waiting_until!) })}{espera.reason ? `: ${espera.reason}` : ''}
            </p>
          {/if}
          <SegmentedPicker value={p.kind} options={opcoesTipo} ariaLabel={m.voz_servico_tipo()}
            onPick={(v) => { if (v !== p.kind) atualizar(i, editTranscriptionProviderTarget(p, { kind: v }, salvo)); }} />
          <div class="campos">
            {#if p.kind === 'whisper_cpp'}
              <p class="ajuda local-help">{m.native_voice_provider_local_help({ server: store.alvo?.label || m.native_voice_provider_current_server() })}</p>
              <a class="link-btn" href="https://github.com/ggml-org/whisper.cpp" target="_blank" rel="noopener noreferrer">{m.native_voice_provider_official()}</a>
              {#each [
                { field: 'executable_path' as const, label: m.native_voice_provider_executable(), placeholder: 'whisper-server' },
                { field: 'model_path' as const, label: m.native_voice_provider_model_file(), placeholder: 'ggml-small.bin' },
                { field: 'language' as const, label: m.native_voice_provider_language(), placeholder: 'pt' },
                { field: 'converter_path' as const, label: m.native_voice_provider_converter(), placeholder: 'ffmpeg' },
              ] as item (item.field)}
                <label class="campo">
                  <span class="rot">{item.label}</span>
                  <input name={item.field} type="text" autocomplete="off" autocapitalize="off" spellcheck={false}
                    value={p[item.field] || ''} placeholder={item.placeholder}
                    oninput={(e) => atualizar(i, { ...p, [item.field]: e.currentTarget.value })} />
                </label>
              {/each}
              {@const local = status?.find((s) => s.id === p.id)}
              {#if local?.state}
                <p class="ajuda" role="status">{local.state === 'ready' ? m.native_voice_provider_local_ready()
                  : local.state === 'starting' ? m.native_voice_provider_local_starting()
                  : local.state === 'failed' ? m.native_voice_provider_local_failed() : m.native_voice_provider_local_not_started()}</p>
                {#if local.error}<p class="aviso erro" role="alert">{local.error}</p>{/if}
              {/if}
            {:else}
            {#if p.kind === 'openai'}
              <label class="campo">
                <span class="rot">{m.native_voice_provider_endpoint()}</span>
                <input type="url" autocomplete="off" value={p.base_url} placeholder="https://api.groq.com/openai/v1"
                  oninput={(e) => atualizar(i, editTranscriptionProviderTarget(p, { base_url: e.currentTarget.value }, salvo))} />
              </label>
            {/if}
            <div class="campo">
              <label class="rot" for={`tp-key-${p.id}`}>{p.kind === 'openai' ? m.native_voice_provider_key_optional() : m.native_voice_provider_key()}</label>
              <!-- O campo nunca recebe a máscara; ela fica ao lado. Password: a chave não aparece na tela. -->
              {#if mascara && p.api_key === mascara}
                <span class="mascara">{mascara} <span class="mascara-nota">{m.config_server_configurada()}</span></span>
              {/if}
              <input id={`tp-key-${p.id}`} type="password" autocomplete="new-password" autocapitalize="off" spellcheck={false}
                value={p.api_key === mascara ? '' : p.api_key}
                placeholder={mascara ? m.config_motores_colar_nova() : m.config_motores_colar()}
                oninput={(e) => atualizar(i, editTranscriptionProviderKey(p, e.currentTarget.value, mantem ? mascara : undefined))} />
              {#if p.kind === 'elevenlabs' && !p.api_key}<span class="falta" role="alert">{m.native_voice_provider_missing_key()}</span>{/if}
            </div>
            <label class="campo">
              <span class="rot">{m.native_voice_provider_model()}</span>
              <input type="text" autocomplete="off" value={p.model} placeholder={p.kind === 'elevenlabs' ? 'scribe_v2' : 'whisper-large-v3'}
                oninput={(e) => atualizar(i, { ...p, model: e.currentTarget.value })} />
            </label>
            {/if}
          </div>
          <input type="file" accept="audio/*,.webm,.m4a" hidden bind:this={audioInputs[p.id]}
            onchange={(e) => { void testAudio(p.id, e.currentTarget.files?.[0]); e.currentTarget.value = ''; }} />
          <button class="btn" disabled={!salvo || JSON.stringify(p) !== JSON.stringify(salvo) || tests[p.id]?.running}
            onclick={() => audioInputs[p.id]?.click()}>{tests[p.id]?.running ? m.native_voice_provider_test_running() : m.native_voice_provider_test_audio()}</button>
          {#if !salvo || JSON.stringify(p) !== JSON.stringify(salvo)}<p class="ajuda">{m.native_voice_provider_test_saved()}</p>{/if}
          {#if tests[p.id]?.error}<p class="aviso erro" role="alert">{tests[p.id].error}</p>{/if}
          {#if tests[p.id]?.text}<p class="ajuda" role="status">{m.native_voice_provider_test_success()}</p><p class="resultado">{tests[p.id].text}</p>{/if}
        </li>
      {/each}
    </ol>
  {/if}
  <button class="btn" onclick={adicionar}>{m.native_voice_provider_add()}</button>
</div>

<style>
  /* Container query, nunca media query: quem aperta a linha é a largura do painel. */
  .servicos { container-type: inline-size; display: flex; flex-direction: column; gap: var(--space-2); margin-top: var(--space-2); }
  .lista { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; }
  .item { display: flex; flex-direction: column; gap: var(--space-2); padding: var(--space-3) 0; border-bottom: 1px solid var(--border-subtle); }
  .item-cabeca { display: flex; align-items: center; gap: var(--space-2); }
  .nome { flex: 1 1 auto; min-width: 0; font-size: var(--text-sm); font-weight: 600; color: var(--text-primary); overflow-wrap: anywhere; }
  .acoes { display: flex; gap: 4px; flex-shrink: 0; }
  .mini {
    width: 32px; height: 32px; border-radius: var(--radius-md); background: transparent;
    color: var(--text-secondary); font-size: var(--text-sm);
  }
  .mini:disabled { opacity: 0.35; }
  .espera { margin: 0; font-size: var(--text-xs); color: var(--warning, var(--text-muted)); }
  .campos { display: grid; grid-template-columns: 1fr; gap: var(--space-2); }
  .local-help { grid-column: 1 / -1; }
  .resultado { margin: 0; white-space: pre-wrap; overflow-wrap: anywhere; }
  @container (min-width: 520px) { .campos { grid-template-columns: 1fr 1fr; } }
  .campo { display: flex; flex-direction: column; gap: 4px; min-width: 0; }
  .rot { font-size: var(--text-xs); font-weight: 600; color: var(--text-secondary); }
  .campo input {
    height: 36px; padding: 0 10px; min-width: 0;
    border: 1px solid var(--border-subtle); border-radius: var(--radius-md);
    background: var(--surface-inset); color: var(--text-primary);
    font-family: var(--font-ui); font-size: var(--text-sm);
  }
  .mascara { font-family: var(--font-mono); font-size: var(--text-xs); color: var(--text-muted); overflow-wrap: anywhere; }
  .mascara-nota { font-family: var(--font-ui); color: var(--success); }
  .falta { font-size: var(--text-xs); color: var(--warning, var(--error)); }
  .ajuda { margin: 0; font-size: var(--text-xs); color: var(--text-muted); line-height: 1.45; }
  .aviso { font-size: var(--text-sm); color: var(--text-muted); margin: 0; }
  .aviso.erro { color: var(--error); }
  .link-btn { margin-left: var(--space-2); padding: 0; background: none; border: none; color: var(--accent); font-size: inherit; }
  .btn {
    align-self: flex-start; height: 40px; padding: 0 var(--space-4); border-radius: var(--radius-md);
    background: var(--surface-raised); color: var(--text-primary); font-size: var(--text-sm); font-weight: 600;
  }
</style>
